'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BarChart3, Crosshair, Swords, Trophy, Users } from 'lucide-react';

type Fighter = { id:number; playerId:string; playerName:string; power:number; kills:number; defeat:number; troops:number; previousPower?:number; previousKills?:number; previousDefeat?:number; previousTroops?:number };
const number=(value:number)=>new Intl.NumberFormat('en-US').format(value||0);
const percent=(current:number,previous?:number)=>previous?`${(((current-previous)/previous)*100).toFixed(2)}%`:'—';
const calc=(fighter:Fighter)=>{const kills=(fighter.previousKills===undefined?0:fighter.kills-fighter.previousKills);const lost=(fighter.previousDefeat===undefined?0:fighter.defeat-fighter.previousDefeat);const net=(fighter.previousTroops===undefined?0:fighter.troops-fighter.previousTroops);return {kills,lost,added:net+lost,efficiency:kills+lost?`${((kills/(kills+lost))*100).toFixed(1)}%`:'—'};};

export default function StatsPage(){
  const [lang,setLang]=useState<'ar'|'en'>('ar');const [fighters,setFighters]=useState<Fighter[]>([]);const ar=lang==='ar';
  useEffect(()=>{fetch('/api/submissions').then(r=>r.ok?r.json():[]).then(setFighters);},[]);
  const totals=useMemo(()=>fighters.reduce((a,f)=>({power:a.power+f.power,kills:a.kills+f.kills,lost:a.lost+calc(f).lost}),{power:0,kills:0,lost:0}),[fighters]);
  return <main className="public-stats" dir={ar?'rtl':'ltr'}><header className="stats-nav"><a href="/" className="brand"><span className="brand-mark">RK</span><span>RK<b>75</b> <i>COMMAND</i></span></a><div><button className="language-toggle" onClick={()=>setLang(ar?'en':'ar')}>{ar?'English':'العربية'}</button><a className="stats-back" href="/"><ArrowLeft size={16}/>{ar?'الرئيسية':'Home'}</a></div></header><section className="stats-hero"><p>{ar?'إحصائيات التحالف':'ALLIANCE STATISTICS'}</p><h1>{ar?'نتائج مقاتلي RK75':'RK75 Fighter Results'}</h1><span>{ar?'آخر إحصائية معتمدة لكل لاعب':'Latest approved scan for every fighter'}</span></section><section className="public-total-grid"><div><Crosshair/><span>{ar?'إجمالي القوة':'Total power'}</span><b>{number(totals.power)}</b></div><div><Swords/><span>{ar?'إجمالي القتلات':'Total kills'}</span><b>{number(totals.kills)}</b></div><div><Users/><span>{ar?'خسائر الفترة':'Period losses'}</span><b>{number(totals.lost)}</b></div><div><Trophy/><span>{ar?'المقاتلون':'Fighters'}</span><b>{fighters.length}</b></div></section><section className="public-table-card"><div className="public-table-head"><div><p>{ar?'الترتيب حسب القتلات':'RANKED BY KILLS'}</p><h2>{ar?'كل إحصائيات اللاعبين':'All player statistics'}</h2></div><BarChart3 size={24}/></div><div className="public-table-scroll"><table><thead><tr><th>#</th><th>{ar?'اللاعب':'Fighter'}</th><th>Power</th><th>{ar?'تغيّر القوة':'Power change'}</th><th>Kills</th><th>{ar?'قتلات جديدة':'Kills gained'}</th><th>{ar?'جنود خسرهم':'Soldiers lost'}</th><th>{ar?'جنود تمت إضافتهم':'Troops added'}</th><th>{ar?'الكفاءة':'Efficiency'}</th></tr></thead><tbody>{fighters.map((fighter,index)=>{const values=calc(fighter);return <tr key={fighter.id}><td className="rank">{index+1}</td><td><b>{fighter.playerName}</b><small>ID {fighter.playerId}</small></td><td>{number(fighter.power)}</td><td className={fighter.previousPower&&fighter.power>=fighter.previousPower?'good':'bad'}>{percent(fighter.power,fighter.previousPower)}</td><td>{number(fighter.kills)}</td><td className="good">{fighter.previousKills===undefined?'—':`+${number(values.kills)}`}</td><td className="bad">{fighter.previousDefeat===undefined?'—':number(values.lost)}</td><td className="gold-cell">{fighter.previousTroops===undefined?'—':`+${number(values.added)}`}</td><td className="good">{values.efficiency}</td></tr>})}</tbody></table>{!fighters.length&&<div className="public-empty">{ar?'ستظهر هنا الإحصائيات بعد اعتماد الإدارة لأوّل إرسال.':'Approved fighter statistics will appear here.'}</div>}</div></section><p className="stats-note">{ar?'إضافات الجنود = صافي تغير الجنود + الجنود المفقودون.':'Troops added = net troop change + soldiers lost.'}</p></main>;
}
