'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BarChart3, Crosshair, Swords, Trophy, Users } from 'lucide-react';

type Fighter={id:number;playerId:string;playerName:string;beforeName?:string|null;power:number;kills:number;defeat:number;troops:number;beforePower?:number|null;beforeKills?:number|null;beforeDefeat?:number|null;beforeTroops?:number|null};
const num=(v:number|undefined|null)=>new Intl.NumberFormat('en-US').format(v??0);
const percent=(value:number,base?:number|null)=>base?`${value>=0?'+':''}${(value/base*100).toFixed(2)}%`:'—';
const stats=(f:Fighter)=>{const has=f.beforePower!=null;const kills=f.beforeKills==null?0:f.kills-f.beforeKills;const losses=f.beforeDefeat==null?0:f.defeat-f.beforeDefeat;const troopNet=f.beforeTroops==null?0:f.troops-f.beforeTroops;return{has,power:has?f.power-(f.beforePower??0):0,kills,losses,troopsAdded:troopNet+losses,lossRate:percent(losses,f.beforeDefeat),troopRate:percent(troopNet,f.beforeTroops)}};

export default function StatsPage(){
 const [lang,setLang]=useState<'ar'|'en'>('ar');const [fighters,setFighters]=useState<Fighter[]>([]);const ar=lang==='ar';
 useEffect(()=>{fetch('/api/submissions?public=1').then(r=>r.ok?r.json():[]).then(setFighters)},[]);
 const totals=useMemo(()=>fighters.reduce((a,f)=>{const s=stats(f);return{power:a.power+f.power,kills:a.kills+f.kills,losses:a.losses+s.losses}},{power:0,kills:0,losses:0}),[fighters]);
 const text=(arAr:string,en:string)=>ar?arAr:en;
 return <main className="comparison-page" dir={ar?'rtl':'ltr'}>
  <header className="comparison-nav"><a href="/" className="neo-brand"><span>RK</span><b>75</b><i>COMMAND</i></a><div><a className="stats-back" href="/accounts">{text('سوق الحسابات','Account market')}</a><button className="lang-switch" onClick={()=>setLang(ar?'en':'ar')}>{ar?'English':'العربية'}</button><a className="stats-back" href="/"><ArrowLeft size={16}/>{text('الرئيسية','Home')}</a></div></header>
  <section className="comparison-intro"><div><p>{text('تقرير المقارنة المباشر','LIVE COMPARISON REPORT')}</p><h1>{text('قائمة أعضاء RK75','RK75 Member Roster')}</h1><span>{text('كل لاعب: قبل وبعد والفروقات الدقيقة والنِّسب.','Every fighter: before, after, exact gains, losses, and percentages.')}</span></div><a className="roster-login" href="/">{text('دخول اللاعب وتعديل إحصائياتي','Player sign in & edit my stats')}</a></section>
  <section className="comparison-totals"><div><Crosshair/><span>{text('إجمالي القوة الحالية','Current total power')}</span><b>{num(totals.power)}</b></div><div className="total-kills"><Swords/><span>{text('إجمالي القتلات','Total kills')}</span><b>{num(totals.kills)}</b></div><div className="total-losses"><Users/><span>{text('خسائر الفترة','Period losses')}</span><b>{num(totals.losses)}</b></div><div className="total-troops"><Trophy/><span>{text('الأعضاء المتعقبون','Tracked members')}</span><b>{fighters.length}</b></div></section>
  <section className="comparison-card"><div className="comparison-title"><div><p>RK75 — BEFORE vs AFTER</p><h2>{text('جدول إحصائيات الأعضاء','Member statistics table')}</h2></div><BarChart3 size={24}/></div><div className="comparison-scroll"><table className="comparison-table"><thead><tr><th rowSpan={2}>#</th><th rowSpan={2}>Player ID</th><th colSpan={4}>{text('اللاعب','PLAYER')}</th><th colSpan={3} className="before-head">{text('قبل','BEFORE')}</th><th colSpan={4} className="after-head">{text('بعد','AFTER')}</th><th colSpan={6} className="change-head">{text('الفرق والنِّسب','CHANGE & PERCENTAGES')}</th></tr><tr><th>{text('الاسم قبل','Name before')}</th><th>{text('الاسم بعد','Name after')}</th><th>{text('تغير؟','Changed?')}</th><th>{text('الحالة','Status')}</th><th>Power</th><th>Kills</th><th>Losses</th><th>Power</th><th>Kills</th><th>Losses</th><th>Troops</th><th>{text('فرق القوة','Power change')}</th><th>{text('قتلات مكتسبة','Kills gained')}</th><th>{text('خسائر مكتسبة','Losses gained')}</th><th>{text('نسبة الخسائر','Loss %')}</th><th>{text('جنود مضافون','Troops added')}</th><th>{text('نسبة زيادة الجنود','Troops %')}</th></tr></thead><tbody>{fighters.map((f,index)=>{const s=stats(f);return <tr key={f.id}><td className="rank">{index+1}</td><td>{f.playerId}</td><td>{f.beforeName??'—'}</td><td><b>{f.playerName}</b></td><td className={f.beforeName&&f.beforeName!==f.playerName?'yes':'muted-cell'}>{f.beforeName?(f.beforeName===f.playerName?text('لا','No'):text('نعم','Yes')):'—'}</td><td><i className="tracked">TRACKED</i></td><td>{s.has?num(f.beforePower):'—'}</td><td className="kill-stat">{s.has?num(f.beforeKills):'—'}</td><td className="loss-stat">{s.has?num(f.beforeDefeat):'—'}</td><td>{num(f.power)}</td><td className="kill-stat">{num(f.kills)}</td><td className="loss-stat">{num(f.defeat)}</td><td className="troop-stat">{num(f.troops)}</td><td className={s.power>=0?'positive':'negative'}>{s.has?`${s.power>=0?'+':''}${num(s.power)}`:'—'}</td><td className="change-kills">{s.has?`+${num(s.kills)}`:'—'}</td><td className="change-losses">{s.has?`+${num(s.losses)}`:'—'}</td><td className="negative">{s.has?s.lossRate:'—'}</td><td className="change-troops">{s.has?`+${num(s.troopsAdded)}`:'—'}</td><td className={s.troopsAdded>=0?'positive':'negative'}>{s.has?s.troopRate:'—'}</td></tr>})}</tbody></table>{!fighters.length&&<div className="public-empty">{text('ستظهر البيانات بعد اعتماد أول إرسال لكل لاعب.','Data appears after the first approved scan.')}</div>}</div></section>
  <p className="stats-note">{text('الأزرق = القتل، الأحمر = الخسائر، الأخضر = الجنود الحاليون أو المضافون. جنود مضافون = صافي تغير الجنود + الجنود المفقودون.','Blue = kills, red = losses, green = current or added troops. Troops added = net troop change + soldiers lost.')}</p>
 </main>;
}
