'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Activity, Check, ChevronRight, Download, Edit3, Globe2, Shield, Sparkles, Swords, Target, Trash2, Users, X, Zap } from 'lucide-react';

type Lang='ar'|'en'; type Role='player'|'admin'; type View='home'|'player'|'admin';
type Scan={id:number;playerId:string;playerName:string;power:number;kills:number;defeat:number;troops:number;note?:string;status:'pending'|'approved'|'rejected';submittedAt:string};
const copy={ar:{members:'قائمة الأعضاء',player:'دخول اللاعبين',admin:'دخول الإدارة',login:'تسجيل الدخول',register:'إنشاء حساب',id:'Player ID',name:'اسم اللاعب',pass:'كلمة المرور',confirm:'تأكيد كلمة المرور',adminPass:'كلمة مرور الإدارة',newAccount:'ليس لديك حساب؟ أنشئ حساباً',hasAccount:'لديك حساب؟ سجل الدخول',home:'الرئيسية',out:'تسجيل الخروج',editMine:'تعديل آخر إحصائياتي',newScan:'إرسال فحص جديد',save:'حفظ التعديلات',send:'إرسال للمراجعة',power:'Power',kills:'Kills',losses:'Defeat in Battle',troops:'Current Troops',note:'ملاحظة اختيارية',command:'غرفة قيادة RK75',all:'كل الأعضاء',online:'متصل الآن',utc:'التوقيت العالمي UTC',open:'فترة الفحص مفتوحة',beforeAfter:'قبل / بعد / الفرق',approved:'معتمد',pending:'بانتظار',rejected:'مرفوض',approve:'اعتماد',reject:'رفض',remove:'حذف اللاعب',edit:'تعديل',export:'تصدير CSV',deleteAsk:'هل تريد حذف اللاعب وكل سجلاته نهائياً؟',welcome:'مرحباً أيها المقاتل',adminWelcome:'لوحة تحكم القائد',accountHint:'يمكنك تعديل آخر إرسال خاص بك أو إنشاء فحص جديد في أي وقت.',adminHint:'عدّل أو احذف أي عضو، وراجع كل الإرسالات من هنا.',createOk:'تم إنشاء حسابك بنجاح.',error:'تحقق من البيانات وحاول مجدداً.',duel:'استعد للقتال',adminDuel:'فتح غرفة القيادة',language:'English'},en:{members:'Member roster',player:'Player sign in',admin:'Admin sign in',login:'Sign in',register:'Create account',id:'Player ID',name:'Player name',pass:'Password',confirm:'Confirm password',adminPass:'Admin password',newAccount:'New here? Create your account',hasAccount:'Already registered? Sign in',home:'Home',out:'Sign out',editMine:'Edit my latest statistics',newScan:'Submit a new scan',save:'Save changes',send:'Send for review',power:'Power',kills:'Kills',losses:'Defeat in Battle',troops:'Current Troops',note:'Optional note',command:'RK75 command room',all:'All members',online:'Online now',utc:'UTC time',open:'Scan period is open',beforeAfter:'Before / after / change',approved:'Approved',pending:'Pending',rejected:'Rejected',approve:'Approve',reject:'Reject',remove:'Delete player',edit:'Edit',export:'Export CSV',deleteAsk:'Delete this player and every record permanently?',welcome:'Welcome, fighter',adminWelcome:'Commander control',accountHint:'Edit your latest entry or submit a new scan whenever you need.',adminHint:'Edit or remove any member and review every submitted scan here.',createOk:'Your account was created.',error:'Check your details and try again.',duel:'Prepare for battle',adminDuel:'Opening command room',language:'العربية'}} as const;
const n=(v:number)=>new Intl.NumberFormat('en-US').format(v||0);
function Brand(){return <a className="neo-brand" href="/"><span>RK</span><b>75</b><i>FATE WAR</i></a>}

export default function Home(){
 const [lang,setLang]=useState<Lang>('ar'),[view,setView]=useState<View>('home'),[gate,setGate]=useState<Role|null>(null),[authMode,setAuthMode]=useState<'register'|'login'>('register'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[entrance,setEntrance]=useState<Role|null>(null),[scans,setScans]=useState<Scan[]>([]),[presence,setPresence]=useState({members:0,online:0}),[utc,setUtc]=useState(''),[editing,setEditing]=useState<Scan|null>(null),[playerEdit,setPlayerEdit]=useState<Scan|null>(null);
 const [auth,setAuth]=useState({playerId:'',name:'',password:'',confirm:''});const blank={name:'',power:'',kills:'',defeat:'',troops:'',note:''};const [draft,setDraft]=useState(blank);const t=copy[lang], rtl=lang==='ar';
 const load=async()=>{const r=await fetch('/api/submissions');if(r.ok)setScans(await r.json())};
 useEffect(()=>{const tick=()=>setUtc(new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{let key=localStorage.getItem('rk75-presence');if(!key){key=crypto.randomUUID();localStorage.setItem('rk75-presence',key)}const ping=async()=>{const r=await fetch('/api/presence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({visitorKey:key})});if(r.ok)setPresence(await r.json())};void ping();const id=setInterval(ping,30000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(view!=='home')void load()},[view]);
 const open=(role:Role)=>{setGate(role);setAuthMode('register');setAuth({playerId:'',name:'',password:'',confirm:''});setNotice('')};
 const authSubmit=async(e:FormEvent)=>{e.preventDefault();if(!gate)return;if(gate==='player'&&authMode==='register'&&auth.password!==auth.confirm){setNotice(rtl?'كلمتا المرور غير متطابقتان.':'Passwords do not match.');return}setBusy(true);const body=gate==='admin'?{role:'admin',password:auth.password}:{role:'player',action:authMode,playerId:auth.playerId,name:auth.name,password:auth.password};const r=await fetch('/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();setBusy(false);if(!r.ok){setNotice(data.error||t.error);return}const next=gate;setGate(null);setEntrance(next);setTimeout(()=>setEntrance(null),8000);setView(next);setNotice(next==='player'&&authMode==='register'?t.createOk:'')};
 const asDraft=(s:Scan)=>({name:s.playerName,power:String(s.power),kills:String(s.kills),defeat:String(s.defeat),troops:String(s.troops),note:s.note||''});
 const savePlayer=async(e:FormEvent)=>{e.preventDefault();setBusy(true);const body={name:draft.name,power:Number(draft.power),kills:Number(draft.kills),defeat:Number(draft.defeat),troops:Number(draft.troops),note:draft.note};const r=await fetch('/api/submissions',{method:playerEdit?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(playerEdit?{...body,id:playerEdit.id}:body)});setBusy(false);if(!r.ok){setNotice(t.error);return}setPlayerEdit(null);setDraft(blank);setNotice(playerEdit? t.save:t.send);void load()};
 const review=async(id:number,status:'approved'|'rejected')=>{await fetch('/api/submissions',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});void load()};
 const saveAdmin=async(e:FormEvent)=>{e.preventDefault();if(!editing)return;setBusy(true);await fetch('/api/submissions',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:editing.id,name:draft.name,power:Number(draft.power),kills:Number(draft.kills),defeat:Number(draft.defeat),troops:Number(draft.troops),note:draft.note})});setBusy(false);setEditing(null);void load()};
 const remove=async(id:string)=>{if(!window.confirm(t.deleteAsk))return;await fetch('/api/submissions',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({playerId:id})});void load()};
 const logout=async()=>{await fetch('/api/session',{method:'DELETE'});setView('home');setScans([]);setNotice('')};
 const exportCsv=()=>{const rows=[['Player ID','Name','Power','Kills','Defeat','Troops','Status'],...scans.map(s=>[s.playerId,s.playerName,s.power,s.kills,s.defeat,s.troops,s.status])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'}));a.download='rk75-members.csv';a.click()};
 const totals=useMemo(()=>scans.filter(s=>s.status==='approved').reduce((x,s)=>({power:x.power+s.power,kills:x.kills+s.kills,losses:x.losses+s.defeat}),{power:0,kills:0,losses:0}),[scans]);
 const langBtn=<button className="lang-switch" onClick={()=>setLang(rtl?'en':'ar')}><Globe2 size={15}/>{t.language}</button>;
 const Auth=gate&&<div className="gate-backdrop"><form className={`gate-card ${gate==='admin'?'gate-admin':''}`} onSubmit={authSubmit}><button className="close" type="button" onClick={()=>setGate(null)}><X/></button><div className="gate-emblem">{gate==='admin'?<Shield/>:<Zap/>}</div><p>RK75 ACCESS</p><h2>{gate==='admin'?t.admin:authMode==='register'?t.register:t.login}</h2><span>{gate==='admin'?(rtl?'بوابة القائد السرية لإدارة التحالف.':'Secure commander access for alliance management.'):(rtl?'أنشئ كلمة المرور بنفسك ثم ادخل للحساب نفسه متى شئت.':'Choose your password, then return to this account whenever you want.')}</span>{gate==='player'&&<><label>{t.id}<input required inputMode="numeric" value={auth.playerId} onChange={e=>setAuth({...auth,playerId:e.target.value.replace(/\D/g,'')})}/></label>{authMode==='register'&&<label>{t.name}<input required value={auth.name} onChange={e=>setAuth({...auth,name:e.target.value})}/></label>}</>}<label>{gate==='admin'?t.adminPass:t.pass}<input required type="password" minLength={gate==='admin'?1:6} value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})}/></label>{gate==='player'&&authMode==='register'&&<label>{t.confirm}<input required type="password" minLength={6} value={auth.confirm} onChange={e=>setAuth({...auth,confirm:e.target.value})}/></label>}{notice&&<small className="form-notice">{notice}</small>}<button className="ember-button" disabled={busy}>{busy?'…':gate==='admin'?t.admin:authMode==='register'?t.register:t.login}<ChevronRight size={18}/></button>{gate==='player'&&<button className="switch-auth" type="button" onClick={()=>setAuthMode(authMode==='register'?'login':'register')}>{authMode==='register'?t.hasAccount:t.newAccount}</button>}</form></div>;
 const Entrance=entrance&&<div className={`duel-entrance ${entrance==='admin'?'duel-admin':''}`}><div className="duel-left"/><div className="duel-right"/><div className="sword-impact"><b>RK75</b><span>{entrance==='admin'?t.adminDuel:t.duel}</span></div><div className="impact-flash"/></div>;
 const Editor=editing&&<div className="gate-backdrop"><form className="gate-card edit-card" onSubmit={saveAdmin}><button type="button" className="close" onClick={()=>setEditing(null)}><X/></button><p>ADMIN EDIT</p><h2>{editing.playerName}</h2><StatsInputs draft={draft} setDraft={setDraft} t={t}/><button className="ember-button" disabled={busy}>{t.save}<Check size={17}/></button></form></div>;
 if(view==='home')return <main className="command-home" dir={rtl?'rtl':'ltr'}><header className="neo-top"><Brand/><nav><a href="/stats">{t.members}</a>{langBtn}<button className="admin-trigger" onClick={()=>open('admin')}><Shield size={16}/>{t.admin}</button></nav></header><section className="command-stage"><div className="stage-copy"><p className="kicker"><Sparkles size={15}/> RK75 — FATE WAR TRACKER</p><h1>{rtl?<>قارن. قُد.<br/><em>انتصر.</em></>:<>Compare. Command.<br/><em>Conquer.</em></>}</h1><p>{rtl?'نظام فخم لمتابعة القوة والقتل والخسائر والجنود لكل عضو، قبل وبعد كل فحص.':'A premium system to track power, kills, losses, and troops for every member — before and after every scan.'}</p><div className="stage-actions"><button className="ember-button" onClick={()=>open('player')}><Swords size={18}/>{t.player}</button><a className="outline-button" href="/stats"><Activity size={18}/>{t.beforeAfter}</a></div></div><aside className="signal-console"><div className="console-top"><span className="pulse"/>{t.open}<b>LIVE</b></div><div className="utc-clock"><small>{t.utc}</small><strong>{utc}</strong></div><div className="radar"><i/><i/><i/><span>RK75</span></div><div className="console-metrics"><div><Users/><span>{t.all}</span><b>{presence.members}</b></div><div><Activity/><span>{t.online}</span><b>{presence.online}</b></div></div><a href="/stats" className="console-roster">{t.members}<ChevronRight size={16}/></a></aside></section>{Auth}{Entrance}</main>;
 if(view==='player')return <main className="fighter-workspace" dir={rtl?'rtl':'ltr'}><header className="workspace-top"><Brand/><div>{langBtn}<button className="plain-link" onClick={logout}>{t.out}</button></div></header><section className="fighter-hero"><p>RK75 / PLAYER ACCOUNT</p><h1>{t.welcome}</h1><span>{t.accountHint}</span><div><button className="outline-button" onClick={()=>{setPlayerEdit(scans[0]||null);setDraft(scans[0]?asDraft(scans[0]):blank)}}><Edit3 size={16}/>{scans[0]?t.editMine:t.newScan}</button><a href="/stats" className="plain-link">{t.members}</a></div></section><section className="fighter-grid"><form className="scan-form" onSubmit={savePlayer}><div className="form-head"><span>{playerEdit?'01 / EDIT':'01 / NEW SCAN'}</span><h2>{playerEdit?t.editMine:t.newScan}</h2></div><StatsInputs draft={draft} setDraft={setDraft} t={t}/><button className="ember-button form-submit" disabled={busy}>{playerEdit?t.save:t.send}<ChevronRight size={18}/></button>{notice&&<p className="form-notice">{notice}</p>}</form><div className="my-scans"><p>MY SUBMISSIONS</p><h2>{t.beforeAfter}</h2>{scans.map(s=><button key={s.id} onClick={()=>{setPlayerEdit(s);setDraft(asDraft(s))}} className="scan-row"><span><b>{s.playerName}</b><small>{new Date(s.submittedAt).toLocaleString()}</small></span><strong>{n(s.power)}</strong><i className={s.status}>{t[s.status]}</i><Edit3 size={15}/></button>)}{!scans.length&&<p className="muted-empty">{rtl?'لا توجد إرسالات بعد.':'No submissions yet.'}</p>}</div></section>{Entrance}</main>;
 return <main className="admin-workspace" dir={rtl?'rtl':'ltr'}><header className="workspace-top"><Brand/><div>{langBtn}<button className="plain-link" onClick={logout}>{t.out}</button></div></header><section className="admin-banner"><div><p>RK75 COMMAND / ADMIN</p><h1>{t.adminWelcome}</h1><span>{t.adminHint}</span></div><div className="admin-buttons"><a href="/stats" className="outline-button"><Users size={16}/>{t.members}</a><button className="ember-button" onClick={exportCsv}><Download size={16}/>{t.export}</button></div></section><section className="admin-kpis"><Kpi icon={<Target/>} label={t.power} value={n(totals.power)}/><Kpi icon={<Swords/>} label={t.kills} value={n(totals.kills)}/><Kpi icon={<Users/>} label={t.losses} value={n(totals.losses)}/><Kpi icon={<Activity/>} label={t.online} value={String(presence.online)}/></section><section className="admin-table-card"><div className="table-title"><div><p>MEMBER CONTROL</p><h2>{t.members}</h2></div><b>{scans.length}</b></div><div className="admin-scroll"><table className="admin-table"><thead><tr><th>{t.id}</th><th>{t.name}</th><th>{t.power}</th><th>{t.kills}</th><th>{t.losses}</th><th>{t.troops}</th><th>{rtl?'الحالة':'Status'}</th><th>{rtl?'إجراءات':'Actions'}</th></tr></thead><tbody>{scans.map(s=><tr key={s.id}><td>{s.playerId}</td><td><b>{s.playerName}</b><small>{new Date(s.submittedAt).toLocaleDateString()}</small></td><td>{n(s.power)}</td><td>{n(s.kills)}</td><td>{n(s.defeat)}</td><td>{n(s.troops)}</td><td><i className={s.status}>{t[s.status]}</i></td><td className="admin-actions">{s.status==='pending'&&<><button title={t.approve} onClick={()=>review(s.id,'approved')}><Check/></button><button title={t.reject} onClick={()=>review(s.id,'rejected')}><X/></button></>}<button title={t.edit} onClick={()=>{setEditing(s);setDraft(asDraft(s))}}><Edit3/></button><button className="danger" title={t.remove} onClick={()=>remove(s.playerId)}><Trash2/></button></td></tr>)}</tbody></table>{!scans.length&&<p className="muted-empty">{rtl?'لا يوجد أعضاء مسجلون بعد.':'No members registered yet.'}</p>}</div></section>{Editor}{Entrance}</main>;
}
function StatsInputs({draft,setDraft,t}:{draft:{name:string;power:string;kills:string;defeat:string;troops:string;note:string};setDraft:(v:any)=>void;t:any}){const number=(key:'power'|'kills'|'defeat'|'troops')=><label>{t[key==='defeat'?'losses':key]}<input required inputMode="numeric" value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value.replace(/\D/g,'')})}/></label>;return <><div className="stat-inputs"><label>{t.name}<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>{number('power')}{number('kills')}{number('defeat')}{number('troops')}</div><label className="note-field">{t.note}<textarea value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>}
function Kpi({icon,label,value}:{icon:any;label:string;value:string}){return <div className="kpi"><span>{icon}</span><small>{label}</small><b>{value}</b></div>}
