'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, ExternalLink, LoaderCircle, Plus, Radio, Star, Trash2, Users } from 'lucide-react';
import { Creator, Lang } from '@/components/creator-card';

const text = { ar: { home: 'الرئيسية', lang: 'English', title: 'إدارة البثوص', sub: 'الصق رابط قناة Kick أو Twitch أو YouTube مرة واحدة، والباقي يتم تلقائيًا.', add: 'إضافة قناة', input: 'https://kick.com/username', creators: 'القنوات المسجلة', loading: 'جارٍ تحميل القنوات…', locked: 'دخول الإدارة مطلوب لإدارة البثوص.', delete: 'حذف', deleteAsk: 'هل تريد حذف هذه القناة نهائيًا؟', featured: 'مميزة', inactive: 'موقوفة', active: 'نشطة', view: 'عرض', empty: 'لم تضف قناة بعد.', saved: 'تمت إضافة القناة. سيظهر وضع البث حالما تتوفر البيانات.', error: 'تعذر إضافة القناة.', live: 'مباشر', offline: 'غير متصل', unknown: 'غير متاح' }, en: { home: 'Home', lang: 'العربية', title: 'Stream control', sub: 'Paste a Kick, Twitch, or YouTube channel link once. The site handles the rest automatically.', add: 'Add channel', input: 'https://kick.com/username', creators: 'Saved creators', loading: 'Loading creators…', locked: 'Administrator access is required to manage streams.', delete: 'Delete', deleteAsk: 'Delete this creator permanently?', featured: 'Featured', inactive: 'Inactive', active: 'Active', view: 'View', empty: 'No creator has been added yet.', saved: 'Channel saved. Live status will appear as soon as data is available.', error: 'The channel could not be added.', live: 'LIVE', offline: 'OFFLINE', unknown: 'UNKNOWN' } } as const;

export default function StreamAdminPage() {
  const [lang, setLang] = useState<Lang>('ar'), [session, setSession] = useState<{ role: string } | null>(null), [creators, setCreators] = useState<Creator[]>([]), [url, setUrl] = useState(''), [notice, setNotice] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false); const t = text[lang]; const rtl = lang === 'ar';
  const load = async () => { setLoading(true); const sessionResponse = await fetch('/api/session'); const current = sessionResponse.ok ? await sessionResponse.json() as { role: string } : null; setSession(current); if (current?.role === 'admin') { const response = await fetch('/api/creators'); if (response.ok) setCreators(await response.json() as Creator[]); } setLoading(false); };
  useEffect(() => { void load(); }, []);
  const add = async (event: FormEvent) => { event.preventDefault(); if (!url.trim()) return; setBusy(true); setNotice(''); const response = await fetch('/api/creators', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url }) }); const result = await response.json().catch(() => ({})) as { error?: string }; setBusy(false); if (!response.ok) { setNotice(result.error || t.error); return; } setUrl(''); setNotice(t.saved); void load(); };
  const change = async (id: number, changes: object) => { await fetch('/api/creators', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, ...changes }) }); void load(); };
  const remove = async (id: number) => { if (!window.confirm(t.deleteAsk)) return; await fetch('/api/creators', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); void load(); };
  return <main className="stream-admin-page" dir={rtl ? 'rtl' : 'ltr'}><header className="media-nav"><a className="neo-brand" href="/"><span>RK</span><b>75</b><i>ADMIN</i></a><nav><a href="/creators">{t.creators}</a><button className="lang-switch" onClick={() => setLang(rtl ? 'en' : 'ar')}>{t.lang}</button><a className="stats-back" href="/"><ArrowLeft size={16}/>{t.home}</a></nav></header><section className="stream-admin-shell"><div className="stream-admin-intro"><p><Radio size={15}/>RK75 / LIVE CONTROL</p><h1>{t.title}</h1><span>{t.sub}</span></div>{loading ? <div className="creator-loading"><LoaderCircle className="spin"/>{t.loading}</div> : session?.role !== 'admin' ? <section className="creator-empty"><Users/><h2>{t.locked}</h2></section> : <><form className="creator-add-form" onSubmit={add}><label>{t.add}<input required type="url" value={url} placeholder={t.input} onChange={(event) => setUrl(event.target.value)}/></label><button className="ember-button" disabled={busy}>{busy ? '…' : <><Plus size={17}/>{t.add}</>}</button></form>{notice && <p className="stream-admin-notice">{notice}</p>}<section className="stream-admin-list"><div><p>RK75 / CREATORS</p><h2>{t.creators}</h2></div>{creators.map((creator) => <article key={creator.id} className={!creator.active ? 'creator-admin-inactive' : ''}><div className="creator-admin-avatar">{creator.avatarUrl ? <img src={creator.avatarUrl} alt=""/> : creator.platformUsername.slice(0, 1).toUpperCase()}</div><div className="creator-admin-info"><b>{creator.displayName || creator.platformUsername}</b><span>{creator.platform.toUpperCase()} · @{creator.platformUsername}</span><i className={creator.isLive ? 'status-live' : creator.liveStatus === 'unknown' ? 'status-unknown' : ''}>{creator.isLive ? t.live : t[creator.liveStatus]}</i></div><div className="creator-admin-actions"><button type="button" className={creator.featured ? 'selected' : ''} onClick={() => void change(creator.id, { featured: !creator.featured })}><Star size={15}/>{t.featured}</button><button type="button" className={!creator.active ? 'selected' : ''} onClick={() => void change(creator.id, { active: !creator.active })}>{creator.active ? t.active : t.inactive}</button><a href={`/live/${encodeURIComponent(creator.slug)}`}><ExternalLink size={15}/>{t.view}</a><button type="button" className="danger" onClick={() => void remove(creator.id)}><Trash2 size={15}/>{t.delete}</button></div></article>)}{!creators.length && <p className="muted-empty">{t.empty}</p>}</section></>}</section></main>;
}
