'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ChevronLeft, ChevronRight, FileText, ImagePlus, Lightbulb, LoaderCircle, Maximize2, Play, Plus, Radio, Trash2, Video, X } from 'lucide-react';

type Lang = 'ar' | 'en';
type Session = { role: 'player' | 'admin'; playerId?: string } | null;
type Asset = { id: number; position: number; url: string; mediaType: 'image' | 'video' };
type Post = { id: number; kind: 'short' | 'article' | 'idea'; title: string; body: string | null; createdAt: string; assets: Asset[] };

const text = {
  ar: { home: 'الرئيسية', lang: 'English', members: 'الأعضاء', market: 'سوق الحسابات', tag: 'RK75 / MEDIA NETWORK', title: 'RK ميديا وشورتس', sub: 'فيديوهات وصور وأفكار ومقالات من مجتمع RK75.', empty: 'لا توجد منشورات حتى الآن.', loading: 'جارٍ تحميل المحتوى…', admin: 'نشر محتوى جديد', type: 'نوع المنشور', short: 'RK شورت', article: 'مقال', idea: 'فكرة', heading: 'العنوان', body: 'النص أو الفكرة', add: 'إضافة صور أو فيديو', upload: 'نشر الآن', publishing: 'جارٍ النشر…', delete: 'حذف', deleteAsk: 'حذف هذا المنشور وكل ملفاته؟', cancel: 'إلغاء', hint: 'حتى 6 ملفات؛ الصورة 6 MB والفيديو MP4 / WebM / MOV حتى 25 MB', access: 'تسجيل دخول الإدارة للنشر', media: 'RK ميديا', close: 'إغلاق', published: 'تم النشر.', needContent: 'أضف عنوانًا أو نصًا أو ملفًا واحدًا على الأقل.', feed: 'أحدث منشورات RK75' },
  en: { home: 'Home', lang: 'العربية', members: 'Members', market: 'Account market', tag: 'RK75 / MEDIA NETWORK', title: 'RK Media & Shorts', sub: 'Videos, images, ideas, and articles from the RK75 community.', empty: 'No posts yet.', loading: 'Loading content…', admin: 'Publish new content', type: 'Post type', short: 'RK Short', article: 'Article', idea: 'Idea', heading: 'Title', body: 'Message or idea', add: 'Add photos or video', upload: 'Publish now', publishing: 'Publishing…', delete: 'Delete', deleteAsk: 'Delete this post and all of its media?', cancel: 'Cancel', hint: 'Up to 6 files; images 6 MB and MP4 / WebM / MOV video 25 MB', access: 'Admin sign in is required to publish', media: 'RK Media', close: 'Close', published: 'Published.', needContent: 'Add a title, text, or at least one media file.', feed: 'Latest from RK75' },
} as const;

export default function MediaPage() {
  const [lang, setLang] = useState<Lang>('ar'), [posts, setPosts] = useState<Post[]>([]), [session, setSession] = useState<Session>(null), [loading, setLoading] = useState(true), [openComposer, setOpenComposer] = useState(false), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [kind, setKind] = useState<Post['kind']>('short'), [title, setTitle] = useState(''), [body, setBody] = useState(''), [files, setFiles] = useState<File[]>([]), [viewer, setViewer] = useState<{ post: Post; index: number } | null>(null);
  const t = text[lang]; const rtl = lang === 'ar';
  const load = async () => { setLoading(true); const [postsResponse, sessionResponse] = await Promise.all([fetch('/api/media'), fetch('/api/session')]); if (postsResponse.ok) setPosts(await postsResponse.json()); setSession(sessionResponse.ok ? await sessionResponse.json() : null); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const previews = useMemo(() => files.map((file) => ({ src: URL.createObjectURL(file), video: file.type.startsWith('video/') })), [files]);
  useEffect(() => () => previews.forEach((preview) => URL.revokeObjectURL(preview.src)), [previews]);
  const addFiles = (incoming: FileList | null) => { if (!incoming) return; const next = Array.from(incoming); if (files.length + next.length > 6) { setNotice(rtl ? 'الحد الأقصى 6 ملفات.' : 'The maximum is 6 files.'); return; } setFiles((current) => [...current, ...next]); };
  const publish = async (event: FormEvent) => { event.preventDefault(); if (!title.trim() && !body.trim() && !files.length) { setNotice(t.needContent); return; } setBusy(true); setNotice(''); const form = new FormData(); form.append('kind', kind); form.append('title', title); form.append('body', body); files.forEach((file) => form.append('assets', file)); const response = await fetch('/api/media', { method: 'POST', body: form }); const result = await response.json().catch(() => ({})) as { error?: string }; setBusy(false); if (!response.ok) { setNotice(result.error || t.needContent); return; } setTitle(''); setBody(''); setFiles([]); setOpenComposer(false); setNotice(t.published); void load(); };
  const remove = async (id: number) => { if (!window.confirm(t.deleteAsk)) return; const response = await fetch('/api/media', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); if (response.ok) void load(); };
  return <main className="media-page" dir={rtl ? 'rtl' : 'ltr'}>
    <header className="media-nav"><a className="neo-brand" href="/"><span>RK</span><b>75</b><i>MEDIA</i></a><nav><a href="/stats">{t.members}</a><a href="/accounts">{t.market}</a><button className="lang-switch" onClick={() => setLang(rtl ? 'en' : 'ar')}>{t.lang}</button><a className="stats-back" href="/"><ArrowLeft size={16}/>{t.home}</a></nav></header>
    <section className="media-hero"><div><p><Radio size={14}/>{t.tag}</p><h1>{t.title}</h1><span>{t.sub}</span></div>{session?.role === 'admin' ? <button className="ember-button" onClick={() => { setOpenComposer(true); setNotice(''); }}><Plus size={17}/>{t.admin}</button> : <a href="/" className="outline-button">{t.access}</a>}</section>
    {notice && <p className="media-notice">{notice}</p>}
    <section className="media-feed"><div className="media-feed-head"><p>{t.tag}</p><h2>{t.feed}</h2></div>{loading ? <div className="media-loading"><LoaderCircle className="spin"/>{t.loading}</div> : posts.map((post) => <PostCard key={post.id} post={post} t={t} admin={session?.role === 'admin'} onOpen={(index) => setViewer({ post, index })} onDelete={() => void remove(post.id)}/>)}</section>
    {!loading && !posts.length && <section className="media-empty"><Radio/><h2>{t.empty}</h2></section>}
    {openComposer && <div className="media-overlay"><form className="media-composer" onSubmit={publish}><button className="close" type="button" onClick={() => setOpenComposer(false)}><X/></button><p>{t.tag}</p><h2>{t.admin}</h2><div className="media-kind-picker">{(['short', 'article', 'idea'] as const).map((value) => <button key={value} type="button" className={kind === value ? 'selected' : ''} onClick={() => setKind(value)}>{value === 'short' ? <Video/> : value === 'article' ? <FileText/> : <Lightbulb/>}{t[value]}</button>)}</div><label>{t.heading}<input value={title} maxLength={120} onChange={(event) => setTitle(event.target.value)}/></label><label>{t.body}<textarea value={body} maxLength={5000} onChange={(event) => setBody(event.target.value)}/></label><section className="media-upload"><div><b>{t.add}</b><small>{t.hint}</small></div><label><ImagePlus size={18}/>{files.length}/6<input type="file" accept="image/*,video/mp4,video/webm,video/quicktime" multiple onChange={(event) => addFiles(event.target.files)}/></label></section>{files.length > 0 && <div className="media-upload-previews">{previews.map((preview, index) => <figure key={preview.src}>{preview.video ? <><video src={preview.src} muted/><Play size={15}/></> : <img src={preview.src} alt=""/>}<button type="button" onClick={() => setFiles(files.filter((_, itemIndex) => itemIndex !== index))}><X size={13}/></button></figure>)}</div>}<div className="media-composer-actions"><button type="button" className="plain-link" onClick={() => setOpenComposer(false)}>{t.cancel}</button><button className="ember-button" disabled={busy}>{busy ? t.publishing : t.upload}<ChevronRight size={17}/></button></div></form></div>}
    {viewer && <MediaViewer post={viewer.post} index={viewer.index} setIndex={(index) => setViewer({ ...viewer, index })} close={() => setViewer(null)} label={t.close}/>} 
  </main>;
}

function PostCard({ post, t, admin, onOpen, onDelete }: { post: Post; t: typeof text.ar | typeof text.en; admin: boolean; onOpen: (index: number) => void; onDelete: () => void }) {
  const icon = post.kind === 'short' ? <Video/> : post.kind === 'article' ? <FileText/> : <Lightbulb/>;
  return <article className={`media-post media-post-${post.kind}`}><div className="media-post-top"><span>{icon}{t[post.kind]}</span><time>{new Date(post.createdAt).toLocaleDateString()}</time>{admin && <button type="button" onClick={onDelete} aria-label={t.delete}><Trash2 size={16}/></button>}</div><h3>{post.title}</h3>{post.body && <p>{post.body}</p>}{post.assets.length > 0 && <div className={`media-post-assets assets-${Math.min(post.assets.length, 3)}`}>{post.assets.map((asset, index) => <button type="button" key={asset.id} onClick={() => onOpen(index)}>{asset.mediaType === 'video' ? <><video src={asset.url} muted playsInline preload="metadata"/><span className="media-play"><Play fill="currentColor" size={19}/></span></> : <img src={asset.url} alt={post.title}/>}<span className="media-expand"><Maximize2 size={14}/></span></button>)}</div>}</article>;
}

function MediaViewer({ post, index, setIndex, close, label }: { post: Post; index: number; setIndex: (index: number) => void; close: () => void; label: string }) {
  const asset = post.assets[index]; if (!asset) return null;
  return <div className="media-lightbox" role="dialog" aria-modal="true" aria-label={post.title} onMouseDown={close}><div className="media-lightbox-panel" onMouseDown={(event) => event.stopPropagation()}><button type="button" className="media-lightbox-close" onClick={close} aria-label={label}><X/></button>{asset.mediaType === 'video' ? <video src={asset.url} controls autoPlay playsInline/> : <img src={asset.url} alt={post.title}/>} {post.assets.length > 1 && <><button type="button" className="media-lightbox-arrow media-lightbox-prev" onClick={() => setIndex((index - 1 + post.assets.length) % post.assets.length)}><ChevronLeft/></button><button type="button" className="media-lightbox-arrow media-lightbox-next" onClick={() => setIndex((index + 1) % post.assets.length)}><ChevronRight/></button></>}<div className="media-lightbox-caption"><b>{post.title}</b><span>{index + 1} / {post.assets.length}</span></div></div></div>;
}
