'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ChevronLeft, ChevronRight, ImagePlus, LoaderCircle, Maximize2, MessageCircle, Play, Plus, ShieldCheck, Trash2, X } from 'lucide-react';

type Lang = 'ar' | 'en';
type Session = { role: 'player' | 'admin'; playerId?: string } | null;
type Media = { id: number; position: number; url: string; contentType: string; mediaType: 'image' | 'video' };
type Listing = { id: number; playerId: string; title: string; mainSpec: string; kingdom: string; totalPower: string; killPoints: string; vipLevel: string; totalTroops: string; price: string; paymentMethods: string[]; ownerDiscord: string; intermediaryDiscord: string | null; status: 'published' | 'sold'; media?: Media[]; images?: Media[] };

const methods = ['PayPal', 'Wise', 'Revolut', 'Swish', 'Bank transfer', 'Crypto', 'Other'];
const paymentLabel = (method: string, lang: Lang) => lang === 'ar' ? ({ 'Bank transfer': 'تحويل بنكي', Other: 'أخرى', Crypto: 'عملات رقمية' }[method] ?? method) : method;
const initialDraft = { title: '', mainSpec: '', kingdom: '', totalPower: '', killPoints: '', vipLevel: '', totalTroops: '', price: '', ownerDiscord: '', intermediaryDiscord: '' };
const copy = {
  ar: { home: 'الرئيسية', lang: 'English', tag: 'RK75 / سوق الحسابات', listingTag: 'RK75 / عرض حساب', cardTag: 'حساب RK75', title: 'سوق حسابات RK75', sub: 'اعرض حسابك بمواصفاته ووسائطه، ثم اتفق مباشرةً مع المشتري عبر Discord.', publish: 'عرض حساب للبيع', signed: 'انشر حسابك الآن', login: 'سجّل دخول اللاعب للنشر', empty: 'لا توجد حسابات معروضة بعد.', owner: 'Discord صاحب الحساب', intermediary: 'Discord الوسيط', price: 'السعر', methods: 'طرق الدفع المتاحة', noMedia: 'لا توجد وسائط مضافة', remove: 'حذف العرض', deleteAsk: 'هل تريد حذف هذا العرض وكل وسائطه؟', close: 'إغلاق', publishTitle: 'انشر حسابك', publishSub: 'أضف حتى 9 صور أو فيديوهات؛ ستظهر وسائل التواصل وطرق الدفع التي تختارها للمشترين.', listingTitle: 'عنوان العرض', mainSpec: 'المواصفات الرئيسية', kingdom: 'المملكة', power: 'إجمالي القوة', kp: 'نقاط القتل (KP)', vip: 'مستوى VIP', troops: 'إجمالي الجنود', chooseMedia: 'أضف صورًا أو فيديوهات للحساب', mediaHint: 'حتى 9 ملفات: الصورة 6 MB، والفيديو MP4 / WebM / MOV حتى 25 MB', cancel: 'إلغاء', publishNow: 'نشر العرض', publishing: 'جارٍ النشر…', success: 'تم نشر الحساب بنجاح.', error: 'تحقق من كل الخانات والوسائط ثم حاول مجدداً.', playerOnly: 'يجب تسجيل الدخول بحساب لاعب لنشر حساب للبيع.', markSold: 'تم البيع', sold: 'مباع', paymentInfo: 'اتفق على الدفع خارج الموقع وتحقق من الطرف الآخر قبل إتمام أي عملية.', members: 'قائمة الأعضاء', mediaHub: 'RK ميديا', openMedia: 'فتح الوسائط بالحجم الكامل', maxMedia: 'الحد الأقصى هو 9 صور أو فيديوهات.' },
  en: { home: 'Home', lang: 'العربية', tag: 'RK75 ACCOUNT EXCHANGE', listingTag: 'RK75 / ACCOUNT LISTING', cardTag: 'RK75 ACCOUNT', title: 'RK75 Account Market', sub: 'List your account with its specs and media, then agree directly with buyers on Discord.', publish: 'List an account', signed: 'Publish your account', login: 'Player sign in to publish', empty: 'No accounts are listed yet.', owner: "Account owner's Discord", intermediary: "Intermediary's Discord", price: 'Price', methods: 'Available payment methods', noMedia: 'No media added', remove: 'Remove listing', deleteAsk: 'Delete this listing and all of its media?', close: 'Close', publishTitle: 'List your account', publishSub: 'Add up to 9 photos or videos. Your selected contact and payment details will be shown to buyers.', listingTitle: 'Listing title', mainSpec: 'Main Spec', kingdom: 'Kingdom', power: 'Total Power', kp: 'Kill Points (KP)', vip: 'VIP Level', troops: 'Total Troops', chooseMedia: 'Add account photos or videos', mediaHint: 'Up to 9 files: images 6 MB, MP4 / WebM / MOV videos 25 MB', cancel: 'Cancel', publishNow: 'Publish listing', publishing: 'Publishing…', success: 'Your account is now listed.', error: 'Check every field and media file, then try again.', playerOnly: 'Sign in with a player account to list an account for sale.', markSold: 'Mark as sold', sold: 'Sold', paymentInfo: 'Agree on payment outside this site and verify the other party before completing any transaction.', members: 'Members', mediaHub: 'RK Media', openMedia: 'Open full-screen media', maxMedia: 'The maximum is 9 photos or videos.' },
} as const;

export default function AccountsPage() {
  const [lang, setLang] = useState<Lang>('ar'), [listings, setListings] = useState<Listing[]>([]), [session, setSession] = useState<Session>(null), [loading, setLoading] = useState(true), [publishing, setPublishing] = useState(false), [showForm, setShowForm] = useState(false), [notice, setNotice] = useState(''), [draft, setDraft] = useState(initialDraft), [chosenMethods, setChosenMethods] = useState<string[]>([]), [uploads, setUploads] = useState<File[]>([]), [activeMedia, setActiveMedia] = useState<Record<number, number>>({}), [viewer, setViewer] = useState<{ listing: Listing; index: number } | null>(null);
  const ar = lang === 'ar'; const t = copy[lang];
  const load = async () => { setLoading(true); const [accountsResponse, sessionResponse] = await Promise.all([fetch('/api/accounts'), fetch('/api/session')]); if (accountsResponse.ok) setListings(await accountsResponse.json()); setSession(sessionResponse.ok ? await sessionResponse.json() : null); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const previews = useMemo(() => uploads.map((file) => ({ url: URL.createObjectURL(file), type: file.type })), [uploads]);
  useEffect(() => () => previews.forEach((preview) => URL.revokeObjectURL(preview.url)), [previews]);
  const toggleMethod = (method: string) => setChosenMethods((current) => current.includes(method) ? current.filter((item) => item !== method) : [...current, method]);
  const addMedia = (files: FileList | null) => { if (!files) return; const incoming = Array.from(files); if (uploads.length + incoming.length > 9) { setNotice(t.maxMedia); return; } setUploads((current) => [...current, ...incoming]); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!session || session.role !== 'player') { setNotice(t.playerOnly); return; } setPublishing(true); setNotice(''); const form = new FormData(); Object.entries(draft).forEach(([key, value]) => form.append(key, value)); chosenMethods.forEach((method) => form.append('paymentMethods', method)); uploads.forEach((file) => form.append('media', file)); const response = await fetch('/api/accounts', { method: 'POST', body: form }); const result = await response.json().catch(() => ({})) as { error?: string }; setPublishing(false); if (!response.ok) { setNotice(result.error || t.error); return; } setDraft(initialDraft); setUploads([]); setChosenMethods([]); setShowForm(false); setNotice(t.success); void load(); };
  const remove = async (id: number) => { if (!window.confirm(t.deleteAsk)) return; const response = await fetch('/api/accounts', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id }) }); if (response.ok) void load(); };
  const markSold = async (id: number) => { const response = await fetch('/api/accounts', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id, status: 'sold' }) }); if (response.ok) void load(); };
  const field = (key: keyof typeof initialDraft, label: string, type = 'text') => <label className="market-field">{label}<input required type={type} value={draft[key]} onChange={(event) => setDraft({ ...draft, [key]: event.target.value })}/></label>;
  return <main className="market-page" dir={ar ? 'rtl' : 'ltr'}>
    <header className="market-nav"><a className="neo-brand" href="/"><span>RK</span><b>75</b><i>COMMAND</i></a><nav><a href="/stats">{t.members}</a><a href="/media">{t.mediaHub}</a><button className="lang-switch" onClick={() => setLang(ar ? 'en' : 'ar')}>{t.lang}</button><a className="stats-back" href="/"><ArrowLeft size={16}/>{t.home}</a></nav></header>
    <section className="market-hero"><div><p>{t.tag}</p><h1>{t.title}</h1><span>{t.sub}</span></div><div className="market-hero-actions">{session?.role === 'player' ? <button className="ember-button" onClick={() => { setShowForm(true); setNotice(''); }}><Plus size={18}/>{t.publish}</button> : <a className="outline-button" href="/"><ShieldCheck size={17}/>{t.login}</a>}<a className="market-home-link" href="/stats">{ar ? 'إحصائيات التحالف' : 'Alliance stats'}<ChevronRight size={16}/></a></div></section>
    {notice && <p className="market-notice">{notice}</p>}
    <section className="market-grid">{loading ? <div className="market-loading"><LoaderCircle className="spin"/>{ar ? 'جارٍ تحميل الحسابات…' : 'Loading accounts…'}</div> : listings.map((listing) => <ListingCard key={listing.id} listing={listing} t={t} lang={lang} isOwner={session?.role === 'admin' || session?.playerId === listing.playerId} active={activeMedia[listing.id] ?? 0} setActive={(index) => setActiveMedia({ ...activeMedia, [listing.id]: index })} onOpen={(index) => setViewer({ listing, index })} onRemove={() => void remove(listing.id)} onSold={() => void markSold(listing.id)}/>)}</section>
    {!loading && !listings.length && <section className="market-empty"><ImagePlus/><h2>{t.empty}</h2><span>{session?.role === 'player' ? t.signed : t.playerOnly}</span></section>}
    <p className="market-safety">{t.paymentInfo}</p>
    {viewer && <MediaViewer listing={viewer.listing} index={viewer.index} close={() => setViewer(null)} setIndex={(index) => setViewer({ ...viewer, index })} label={t.close}/>}
    {showForm && <div className="market-overlay"><form className="listing-form" onSubmit={submit}><button className="close" type="button" onClick={() => setShowForm(false)}><X/></button><p>{t.listingTag}</p><h2>{t.publishTitle}</h2><span>{t.publishSub}</span><div className="listing-fields">{field('title', t.listingTitle)}<label className="market-field market-wide">{t.mainSpec}<textarea required value={draft.mainSpec} onChange={(event) => setDraft({ ...draft, mainSpec: event.target.value })}/></label>{field('kingdom', t.kingdom)}{field('totalPower', t.power)}{field('killPoints', t.kp)}{field('vipLevel', t.vip)}{field('totalTroops', t.troops)}{field('price', t.price)}{field('ownerDiscord', t.owner)}{field('intermediaryDiscord', t.intermediary)}</div><section className="payment-picker"><b>{t.methods}</b><div>{methods.map((method) => <label key={method}><input type="checkbox" checked={chosenMethods.includes(method)} onChange={() => toggleMethod(method)}/><span>{paymentLabel(method, lang)}</span></label>)}</div></section><section className="photo-picker"><div><b>{t.chooseMedia}</b><small>{t.mediaHint}</small></div><label><ImagePlus size={18}/><span>{uploads.length}/9</span><input type="file" accept="image/*,video/mp4,video/webm,video/quicktime" multiple onChange={(event) => addMedia(event.target.files)}/></label></section>{uploads.length > 0 && <div className="photo-preview-strip">{previews.map((preview, index) => <figure key={preview.url}>{preview.type.startsWith('video/') ? <><video src={preview.url} muted/><Play className="preview-play" size={18}/></> : <img src={preview.url} alt=""/>}<button type="button" onClick={() => setUploads(uploads.filter((_, uploadIndex) => uploadIndex !== index))}><X size={13}/></button></figure>)}</div>}<div className="listing-form-actions"><button className="plain-link" type="button" onClick={() => setShowForm(false)}>{t.cancel}</button><button className="ember-button" disabled={publishing}>{publishing ? t.publishing : t.publishNow}<ChevronRight size={17}/></button></div></form></div>}
  </main>;
}

function ListingCard({ listing, t, lang, isOwner, active, setActive, onOpen, onRemove, onSold }: { listing: Listing; t: typeof copy.ar | typeof copy.en; lang: Lang; isOwner: boolean; active: number; setActive: (index: number) => void; onOpen: (index: number) => void; onRemove: () => void; onSold: () => void }) {
  const media = listing.media ?? listing.images ?? []; const current = media[active] ?? media[0]; const index = current ? Math.max(0, media.findIndex((item) => item.id === current.id)) : 0;
  return <article className={`listing-card ${listing.status === 'sold' ? 'listing-sold' : ''}`}><div className="listing-image">{current ? <button type="button" className="listing-media-open" onClick={() => onOpen(index)} aria-label={t.openMedia}>{current.mediaType === 'video' ? <><video src={current.url} muted playsInline preload="metadata"/><span className="media-play"><Play fill="currentColor" size={20}/></span></> : <img src={current.url} alt={listing.title}/>}<span className="media-expand"><Maximize2 size={15}/></span></button> : <div className="listing-image-empty"><ImagePlus/><span>{t.noMedia}</span></div>}{listing.status === 'sold' && <b className="sold-stamp">{t.sold}</b>}{media.length > 1 && <><button className="gallery-arrow gallery-prev" type="button" onClick={() => setActive((index - 1 + media.length) % media.length)}><ChevronLeft/></button><button className="gallery-arrow gallery-next" type="button" onClick={() => setActive((index + 1) % media.length)}><ChevronRight/></button><div className="gallery-dots">{media.map((item, itemIndex) => <button type="button" key={item.id} className={itemIndex === index ? 'active' : ''} onClick={() => setActive(itemIndex)}/>)}</div></>}</div><div className="listing-body"><div className="listing-heading"><div><p>{t.cardTag}</p><h2>{listing.title}</h2></div><b>{listing.price}</b></div><p className="listing-spec">{listing.mainSpec}</p><dl className="listing-stats"><div><dt>{t.kingdom}</dt><dd>{listing.kingdom}</dd></div><div><dt>{t.power}</dt><dd>{listing.totalPower}</dd></div><div><dt>{t.kp}</dt><dd>{listing.killPoints}</dd></div><div><dt>{t.vip}</dt><dd>{listing.vipLevel}</dd></div><div><dt>{t.troops}</dt><dd>{listing.totalTroops}</dd></div></dl><div className="listing-methods"><span>{t.methods}</span><div>{listing.paymentMethods.map((method) => <b key={method}>{paymentLabel(method, lang)}</b>)}</div></div><div className="listing-contacts"><div><MessageCircle size={16}/><span>{t.owner}</span><b>{listing.ownerDiscord}</b></div><div><ShieldCheck size={16}/><span>{t.intermediary}</span><b>{listing.intermediaryDiscord}</b></div></div>{isOwner && <div className="listing-owner-actions">{listing.status !== 'sold' && <button type="button" className="listing-sold-button" onClick={onSold}><ShieldCheck size={15}/>{t.markSold}</button>}<button type="button" className="listing-delete" onClick={onRemove}><Trash2 size={15}/>{t.remove}</button></div>}</div></article>;
}

function MediaViewer({ listing, index, setIndex, close, label }: { listing: Listing; index: number; setIndex: (index: number) => void; close: () => void; label: string }) {
  const media = listing.media ?? listing.images ?? []; const item = media[index] ?? media[0]; if (!item) return null;
  return <div className="media-lightbox" role="dialog" aria-modal="true" aria-label={listing.title} onMouseDown={close}><div className="media-lightbox-panel" onMouseDown={(event) => event.stopPropagation()}><button type="button" className="media-lightbox-close" onClick={close} aria-label={label}><X/></button>{item.mediaType === 'video' ? <video src={item.url} controls autoPlay playsInline/> : <img src={item.url} alt={listing.title}/>} {media.length > 1 && <><button type="button" className="media-lightbox-arrow media-lightbox-prev" onClick={() => setIndex((index - 1 + media.length) % media.length)}><ChevronLeft/></button><button type="button" className="media-lightbox-arrow media-lightbox-next" onClick={() => setIndex((index + 1) % media.length)}><ChevronRight/></button></>}<div className="media-lightbox-caption"><b>{listing.title}</b><span>{index + 1} / {media.length}</span></div></div></div>;
}
